server:
  port: 8080  # ← 이게 8081이나 다른 숫자면 그 포트로 요청 보내야 함

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qnb_database
    username: root
    password: "Dang1216@@"
    driver-class-name: com.mysql.cj.jdbc.Driver

  spring:
    jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.MySQL8Dialect
          globally_quoted_identifiers: true
          naming:
            physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    datasource:
      url: jdbc:mysql://localhost:3306/qnb_database
      username: root
      password: Dang1216@@



jwt:
  secret: my-very-secret-jwt-key-that-should-be-long
  expiration: 3600000 //키 외부화와 만료 시간 설정